feat: Service for vso tasks rotate
Vanilla-OS/desktop-image pull request #140
Opened 2024-06-22 22:14 UTC by nellfs

closes #136 

This removes the need to create a autostart file directly into the home directory with Vanilla System Operator

https://github.com/Vanilla-OS/vanilla-system-operator/blob/05757fb763d43645db2c6ce8b4796f831f928318/core/tasks.go#L271-L303

2024-06-23 21:43 UTC, taukakao commented
This file needs to be removed:
https://github.com/Vanilla-OS/desktop-image/blob/87b2dbf239972d03452cc5f10fcc9f8d4f422d66/modules/.171.vso-tasks-rotation-autostart.yml.swp

It's a state file that got created by some text editor.

2024-06-23 23:00 UTC, taukakao requested changes
This file needs to be removed:
https://github.com/Vanilla-OS/desktop-image/blob/87b2dbf239972d03452cc5f10fcc9f8d4f422d66/modules/.171.vso-tasks-rotation-autostart.yml.swp

It's a state file that got created by some text editor.

2024-06-23 23:27 UTC, nellfs commented
> This file needs to be removed: https://github.com/Vanilla-OS/desktop-image/blob/87b2dbf239972d03452cc5f10fcc9f8d4f422d66/modules/.171.vso-tasks-rotation-autostart.yml.swp
> 
> It's a state file that got created by some text editor.

Hadn't noticed, I think my editor failed to delete this for some weird reason, now it should be okay

2024-06-23 23:28 UTC, taukakao approved these changes
LGTM

2024-06-23 23:29 UTC, taukakao commented
Please squash the commits into one before you merge

2024-06-24 07:29 UTC, mirkobrombin requested changes

2024-06-24 07:29 UTC, mirkobrombin commented on modules/171-vso-tasks-rotation-autostart.yml
I would add this to the `vanilla-system-operator.yml` file, as a submodule

2024-06-25 06:46 UTC, mirkobrombin approved these changes
LGTM! Remember to squash all commits into one.

2024-06-25 23:20 UTC, nellfs commented
> LGTM! Remember to squash all commits into a single one `feat[close #136]: Add service for vso tasks rotation`

Commits have been squashed!

2024-06-25 23:29 UTC, taukakao approved these changes
LGTM

2024-06-26 01:39 UTC, merged